apiVersion: v1
kind: Service
metadata:
  name: redis-0
  labels:
    app: redis-0
    app.kubernetes.io/component: redis-0
    app.kubernetes.io/instance: redis-0
  annotations:
    metallb.universe.tf/address-pool: pool-01
spec:
  type: LoadBalancer
  ports:
  - port: 6379
    targetPort: 6379
    name: redis-0
  selector:
    statefulset.kubernetes.io/pod-name: redis-0

---

apiVersion: v1
kind: Service
metadata:
  name: redis-1
  labels:
    app: redis-1
    app.kubernetes.io/component: redis-1
    app.kubernetes.io/instance: redis-1
  annotations:
    metallb.universe.tf/address-pool: pool-01
spec:
  type: LoadBalancer
  ports:
  - port: 6379
    targetPort: 6379
    name: redis-1
  selector:
    statefulset.kubernetes.io/pod-name: redis-1

---

apiVersion: v1
kind: Service
metadata:
  name: redis-2
  labels:
    app: redis-2
    app.kubernetes.io/component: redis-2
    app.kubernetes.io/instance: redis-2
  annotations:
    metallb.universe.tf/address-pool: pool-01
spec:
  type: LoadBalancer
  ports:
  - port: 6379
    targetPort: 6379
    name: redis-2
  selector:
    statefulset.kubernetes.io/pod-name: redis-2