redissentinelgo:
  redis:
    password: xxxxxx                 # redis密码
    sentinel:
      master: mymaster               # 集群名称
      nodes:
        - 192.168.1.1:5000           # sentinel连接地址
      password: xxxxxx               # sentinel密码
